### ISSUE TITLE
in institutions detailed view > affiliated persons, please add space between forename and surname

### ISSUE THREAD

**Issue by vanyh** [acdh-oeaw/tei-abstracts-app#10]

**Comment by csae8092** [comment]
locally on eXist-db 3.0 spaces are there, but obviously not on the server (eXist-db RC 3.0). Since we plan to update this eXist-db in near future, I'd like to wait and see if this solves the problem before changing something in the apps code base

**Comment by csae8092** [comment]
installed application test-wise on an eXist-db 3.1 instance on one of ACDH-OeAW internal server and whitespace are handled properly. So no code change needed, just some eXist-db upgrade on our publish/production server. Might take place in the next couple of weeks

**Comment by csae8092** [comment]
production server is now also exist-db 3.1 (and will soon be 3.2), so problem solved by itself. Wonderful :)
