### ISSUE TITLE
in person single view, change heading from <key> to <forename> <surname>

### ISSUE THREAD

**Issue by vanyh** [acdh-oeaw/tei-abstracts-app#16]

**Comment by vanyh** [comment]
...same goes for countries

**Comment by csae8092** [comment]
I guess this page is meant: https://tei2016app.acdh.oeaw.ac.at/pages/hits.html?searchkey=genID9ca45be867443c12e5f7b24c454c15ae

Adding pers- or placeName info is possible but would need some thinking and coding. Therefore I'd go the easy way and remove the this heading
