### ISSUE TITLE
capture&redirect the "_query" parameter

### ISSUE THREAD

**Issue by vanyh** [acdh-oeaw/tei-abstracts-app#24]
Would those guys using eXist-db consider to capture&redirect the "_query" parameter (or at least a set of function names) to avoid offering an open proxy like in this example:
https://tei2016app.acdh.oeaw.ac.at/data/?_query=xquery%20version%20%223.1%22;response:stream-binary(%20xs:base64Binary(%20data(httpclient:get(xs:anyURI(%22http://24.media.tumblr.com/tumblr_lt8vrdas9o1qb8xalo1_400.jpg%22),%20false(),%20())//httpclient:body))%20,%20%22image/jpg%22)
If you are using Apache you might want to
        RewriteEngine on
        RewriteCond %{QUERY_STRING} _query=
        RewriteRule (.*) $1? [R=permanent]

((comment by Mathias Göbel))

**Comment by csae8092** [comment]
fixed
https://redmine.acdh.oeaw.ac.at/issues/8104
