### ISSUE TITLE
please replace pics on start page (use images provided, without captions)

### ISSUE THREAD

**Issue by vanyh** [acdh-oeaw/tei-abstracts-app#7]
![image](https://cloud.githubusercontent.com/assets/23290317/23504558/58f3f4e6-ff40-11e6-9d88-a25e41653ff2.png)
![image](https://cloud.githubusercontent.com/assets/23290317/23504577/71d380e4-ff40-11e6-8ad1-279d27fd6c9d.png)
![image](https://cloud.githubusercontent.com/assets/23290317/23504590/87cf4162-ff40-11e6-8b13-9ebf2953523a.png)
![image](https://cloud.githubusercontent.com/assets/23290317/23504608/9e717d40-ff40-11e6-8614-0033756fcedc.png)
![image](https://cloud.githubusercontent.com/assets/23290317/23504627/aa8416e2-ff40-11e6-80e0-a12c759bf755.png)

**Comment by csae8092** [comment]
please provide some text for credits (which will appear on mouse-over

**Comment by vanyh** [comment]
as credits, please use:
"More conference pictures by Syd Bauman & Sandra Lehecka at http://tei2016.acdh.oeaw.ac.at/photo-gallery"
